on: push
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Run tests
      run: |
        pip install .
        render50 -h
        touch foo.c && render50 -o foo.pdf foo.c && test -f foo.pdf
    - name: Release
        uses: softprops/action-gh-release@v1
